### ISSUE TITLE
Handle OTP on campus and non-campus network separately

### ISSUE THREAD

**Issue by proffapt** [metakgp/iitkgp-erp-auto-login#1]
When connected to campus network there is no need for OTP. This means that we could just directly login as it was before.

Here's a possible solutions:
- Use https://heimdall.metakgp.org to retrieve what's the case and handle it.

**Comment by chirag-ghosh** [comment]
Better to move that backend to metakgp server once and for all. cc @harshkhandeparkar (The Father of [Metaploy](https://github.com/metakgp/metaploy))

**Comment by proffapt** [comment]
hn woh bola tha mein already.. hai mere todo list mein..

**Comment by harshkhandeparkar** [comment]
> Better to move that backend to metakgp server once and for all. cc @harshkhandeparkar (The Father of [Metaploy](https://github.com/metakgp/metaploy))

Where's the code for this?

**Comment by proffapt** [comment]
https://github.com/chirag-ghosh/heimdall here

**Comment by harshkhandeparkar** [comment]
> https://github.com/chirag-ghosh/heimdall here

Let's move it to metakgp then. @chirag-ghosh ?

**Comment by chirag-ghosh** [comment]
Tum bole aur hum na kare?

**Comment by proffapt** [comment]
OTP is always required now :)
