### ISSUE TITLE
Handle OTP while login

### ISSUE THREAD

**Issue by Bikram-ghuku** [metakgp/iitkgp-erp-auto-login#2]
## Add a functionality to enter email OTP while signing-in to ERP

ERP has mandated email OTP for all login

**Comment by Bikram-ghuku** [comment]
Can I work on this issue?

**Comment by proffapt** [comment]
Go ahead.

**Comment by Bikram-ghuku** [comment]
The Code works on Chrome Extension without any problem, the firefox version doesn't work...
