### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by proffapt** [metakgp/iitkgp-erp-auto-login#3]
Update the format of documentation according to [this](https://github.com/metakgp/README.md)

**Comment by Bikram-ghuku** [comment]
### New build instructions

- Build from source (for development)

  1. Clone the repository
     ```bash
     git clone https://github.com/siddsarkar/iitkgp-erp-auto-login-extension.git
     ```
  2. Cd into the repository
     ```bash
     cd iitkgp-erp-auto-login-extension
     ```
  3. Install dependencies
     ```bash
     npm install
     ```
  4. Build the extension and watch for changes
     ```bash
     npm run start
     ```
  5. In a new terminal (once only)
      ```bash
      npm install --global web-ext # install web-ext globally
      ```
  6. The above step will create a `addon` folder with the extension in it.
      ```bash
      cd addon
      ```

  7. Run the extension using [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) as below
     ```bash
     web-ext run # run the extension for firefox
     web-ext run -t chromium # (or) run the extension for chrome
     ```
  7. Check that the extension is loaded by opening the extensions page in Firefox `about:addons` or in Chrome `chrome://extensions/`.

**Comment by Bikram-ghuku** [comment]
- Build from source (for production)

  1. Clone the repository
     ```bash
     git clone https://github.com/siddsarkar/iitkgp-erp-auto-login-extension.git
     ```
  2. Cd into the repository
     ```bash
     cd iitkgp-erp-auto-login-extension
     ```
  3. Install dependencies
     ```bash
     npm install
     ```
  4. Build the extension and watch for changes
     ```bash
     npm run build-prod
     ```
  6. The above step will create a `addon` folder with the extension in it.

**Comment by Bikram-ghuku** [comment]
# Please update the setup instructions to this in the README

**Comment by proffapt** [comment]
@Bikram-ghuku can you take up this issue? Make sure to follow the template of readme. And you can deviate in middle sections (refer to: iqps-go repository). And give proper credits to the original author.

**Comment by Bikram-ghuku** [comment]
Okay, sure

**Comment by proffapt** [comment]
Do it ASAP.
